CREATE TABLE `commande` (
  `IDCOMMANDE`       INT(128) NOT NULL,
  `IDCLIENT`         INT(128)     DEFAULT NULL,
  `MONTANT`          VARCHAR(200) DEFAULT NULL,
  `TRANSID`          VARCHAR(200) DEFAULT NULL,
  `ABONNEMENT`       VARCHAR(200) DEFAULT NULL,
  `METHODE`          VARCHAR(200) DEFAULT NULL,
  `PAYID`            VARCHAR(200) DEFAULT NULL,
  `BUYERNAME`        VARCHAR(200) DEFAULT NULL,
  `TRANSSTATUS`      VARCHAR(200) DEFAULT NULL,
  `SIGNATURE`        VARCHAR(200) DEFAULT NULL,
  `PHONE`            VARCHAR(200) DEFAULT NULL,
  `ERRORMESSAGE`     VARCHAR(200) DEFAULT NULL,
  `STATUT`           VARCHAR(200) DEFAULT NULL,
  `DATECREATION`     DATETIME     DEFAULT NULL,
  `DATEMODIFICATION` DATETIME     DEFAULT NULL,
  `DATEPAIEMENT`     DATETIME     DEFAULT NULL
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;


ALTER TABLE `commande`
  ADD PRIMARY KEY (`IDCOMMANDE`),
  ADD KEY `pk_commande` (`IDCOMMANDE`);
--  ADD KEY `index_fk_client_commande` (`IDCLIENT`);


ALTER TABLE `commande`
  MODIFY `IDCOMMANDE` INT(128) NOT NULL AUTO_INCREMENT;

-- Si vous voulez lier cette table à une table cliente dans votre projet :
-- ALTER TABLE `commande` ADD CONSTRAINT `fk_client_commande` FOREIGN KEY (`IDCLIENT`) REFERENCES `client` (`IDCLIENT`);--
